<!DOCTYPE html>
<html lang="en-US"><head>
<script src="lec05_tables_that_tell_the_truth_files/libs/clipboard/clipboard.min.js"></script>
<script src="lec05_tables_that_tell_the_truth_files/libs/quarto-html/tabby.min.js"></script>
<script src="lec05_tables_that_tell_the_truth_files/libs/quarto-html/popper.min.js"></script>
<script src="lec05_tables_that_tell_the_truth_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="lec05_tables_that_tell_the_truth_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lec05_tables_that_tell_the_truth_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="lec05_tables_that_tell_the_truth_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="">
  <title>Cleaning tabular data</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="lec05_tables_that_tell_the_truth_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="lec05_tables_that_tell_the_truth_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="lec05_tables_that_tell_the_truth_files/libs/revealjs/dist/theme/quarto-5b332574619179445ab88806626e2cd7.css">
  <link href="lec05_tables_that_tell_the_truth_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="lec05_tables_that_tell_the_truth_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="lec05_tables_that_tell_the_truth_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="lec05_tables_that_tell_the_truth_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#faf7f2" class="quarto-title-block center">
  <h1 class="title">Cleaning tabular data</h1>
  <p class="subtitle">Session 5 · Fri Oct 9 · Book sections 2.3–2.4</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="section" class="slide level2" data-background-color="#faf7f2">
<h2></h2>
<p><span class="lecture-icon">🧮</span></p>
<h3 id="todays-question">Today’s question</h3>
<p>Cleaning changes the data before a model sees it.</p>
<p><strong>Which unusual values in a table are recording errors, and which are real measurements?</strong></p>
<div class="dim">
<p>Reading: <a href="https://geo-smart.github.io/mlgeo-book/pandas-rendered">2.3 Pandas</a> · <a href="https://geo-smart.github.io/mlgeo-book/dataframes-prep">2.4 DataFrame preparation</a></p>
</div>
<aside class="notes">
<p>Frame the session with Wednesday’s curation map: today answers its third row, “does the table record what happened: missing values, types, joins?” Wednesday named the streams and formats; today is the tabular stream, and specifically what happens between “the file opens” and “the data are trusted.” Everyone expects dirty data. The harder problem is cleaning that changes the science without anyone noticing: deleting the evolved granites along with the bad zeros, or trusting values an instrument made up. Every decision today is graded against planted truth. Ask the room: who has ever deleted rows from a dataset? What was the rule, and who reviewed it? Keep the answers; the AGENTS.md slide near the end returns to them.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="literature-example-ocean-temperatures-in-the-1940s" class="slide level2 smaller">
<h2>Literature example: ocean temperatures in the 1940s</h2>
<div class="badge-row">
<p><span class="gb src">📍 In-situ sensor</span> <span class="gb sys ocean">🌊 Ocean</span> <span class="gb disc air">🌡️ Atmospheric &amp; climate science</span></p>
</div>
<div class="columns">
<div class="column" style="width:40%;">
<div class="lit-card">
<p><span class="lit-msg">Global-mean sea surface temperature drops by about 0.3 °C in late 1945, when the reports switch from US ships measuring engine-intake water to UK ships measuring water hauled up in buckets.</span></p>
<p><span class="lit-cite">Thompson, Kennedy, Wallace &amp; Jones (2008). <em>Nature</em>, 453, 646–649.</span></p>
</div>
<p><strong>One data sample is one ship report</strong> (ICOADS release 3.1)</p>
<div class="records">
<table class="caption-top">
<thead>
<tr class="header">
<th>date</th>
<th style="text-align: right;">lat</th>
<th style="text-align: right;">lon</th>
<th style="text-align: right;">SST °C</th>
<th>method</th>
<th>country</th>
<th>deck</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1945-07-01</td>
<td style="text-align: right;">52.5</td>
<td style="text-align: right;">−178.5</td>
<td style="text-align: right;">15.6</td>
<td></td>
<td></td>
<td>195 US Navy logs</td>
</tr>
<tr class="even">
<td>1945-07-01</td>
<td style="text-align: right;">38.5</td>
<td style="text-align: right;">−64.5</td>
<td style="text-align: right;">24.4</td>
<td></td>
<td></td>
<td>195 US Navy logs</td>
</tr>
<tr class="odd">
<td>1945-12</td>
<td style="text-align: right;">14.5</td>
<td style="text-align: right;">120.8</td>
<td style="text-align: right;">27.8</td>
<td></td>
<td>UK</td>
<td>245 Royal Navy logs</td>
</tr>
<tr class="even">
<td>1945-12</td>
<td style="text-align: right;">−33.8</td>
<td style="text-align: right;">151.2</td>
<td style="text-align: right;">21.1</td>
<td></td>
<td>UK</td>
<td>245 Royal Navy logs</td>
</tr>
</tbody>
</table>
</div>
<p><span class="dim">The method column is blank for 96% of the 459,981 reports from 1945, so the method has to be inferred from the deck and the country.</span></p>
</div><div class="column" style="width:60%;">
<p><img data-src="figs/lit_sst_1945/sst_1945_map.png" style="width:100.0%"></p>
<p><img data-src="figs/lit_sst_1945/sst_1945_series.png" style="width:100.0%"></p>
</div></div>
<div class="takeaway">
<p>Raw ICOADS today: −0.4 °C from late 1945 to mid-1946, as the US share of reports falls from 76% to 33%.</p>
</div>
<aside class="notes">
<p>Four minutes; this is the one paper the lecture tells in full. Geoscience first: sea surface temperature since the 1850s comes mostly from ships, and the map shows the 1945 reports, which follow wartime shipping lanes and convoy routes and leave most of the Southern Ocean empty. Then the table: each data sample is one report with a date, a position, a temperature, and columns that record how it was measured (SI, the method code: 0 bucket, 1 engine intake), which country reported it (C1), and which archive it came from (the deck: 195 is US Navy ship logs, 245 Royal Navy ship logs 1938–47, from the ICOADS code tables). In 1945 the method column is blank for 96% of reports, so the method is a cleaning decision inferred from the deck. Thompson et al.&nbsp;(2008) found a drop of about 0.3 °C in late 1945 in the record of the time and traced it to the change in national origin: US engine-intake readings run warm, uninsulated UK bucket readings run cool. The figure is our reconstruction from open data with today’s ICOADS release 3.1, which contains many more digitized logbooks than the 2008 version: the raw global mean (black, three-month running mean of the ICOADS 2° monthly means from NOAA PSL, no bias adjustment) falls by about 0.4 °C from late 1945 to mid-1946, and the deck counts from the IMMA files (bottom) show the US share dropping from about 76% in September 1945 to about 33% in March 1946. The bias-adjusted HadSST4 record (teal) warms the bucket-dominated years before 1941 by about 0.3 °C but still shows part of the 1945–46 drop; Chan and Huybers (2021, next slide) revisited the corrections deck by deck. Everything here is regenerated by figscripts/sst_1945_discontinuity.py. Reading code for the students who ask: the IMMA files are fixed-width text, so pandas.read_fwf with column positions (year 1–4, latitude 13–17, longitude 18–23, method 84–85, SST 86–89, deck 119–121) reads them.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-same-problem-in-other-geoscience-tables" class="slide level2 smaller">
<h2>The same problem in other geoscience tables</h2>
<!-- Literature anchors for lecture 5, second literature slide (the first,
     Thompson et al. 2008, is told in full in the deck). Edit THIS file to
     update the papers; the deck includes it verbatim. Keep four cards:
     a number or term first, one sentence, then the citation. -->
<div class="columns">
<div class="column" style="width:50%;">
<div class="lit-card">
<p><span class="lit-num">0.12 °C</span></p>
<p><span class="lit-msg">Buoys read cooler than ships. Correcting the offset removed the apparent slowdown of warming after 1998.</span></p>
<p><span class="lit-cite">Karl, T. R., et al.&nbsp;(2015). Possible artifacts of data biases in the recent global surface warming hiatus. <em>Science</em>, 348, 1469–1472.</span></p>
</div>
<div class="lit-card">
<p><span class="lit-num">1941–1945</span></p>
<p><span class="lit-msg">Estimating offsets separately for each ship deck and country removes the anomalous warmth of the World War II years.</span></p>
<p><span class="lit-cite">Chan, D., &amp; Huybers, P. (2021). Correcting observational biases in sea surface temperature observations removes anomalous warmth during World War II. <em>Journal of Climate</em>, 34, 4585–4602.</span></p>
</div>
</div><div class="column" style="width:50%;">
<div class="lit-card">
<p><span class="lit-num">M<sub>c</sub></span></p>
<p><span class="lit-msg">Below the magnitude of completeness a catalog misses events, and the b-value depends on where the cut is placed.</span></p>
<p><span class="lit-cite">Woessner, J., &amp; Wiemer, S. (2005). Assessing the quality of earthquake catalogues: Estimating the magnitude of completeness and its uncertainty. <em>Bulletin of the Seismological Society of America</em>, 95, 684–698.</span></p>
</div>
<div class="lit-card">
<p><span class="lit-num bad">&lt; DL</span></p>
<p><span class="lit-msg">Substituting the detection limit, or half of it, for nondetects in water-quality data biases means and trends.</span></p>
<p><span class="lit-cite">Helsel, D. R. (2006). Fabricating data: How substituting values for nondetects can ruin results, and what can be done about it. <em>Chemosphere</em>, 65, 2434–2439.</span></p>
</div>
</div></div>
<div class="takeaway">
<p>Ocean temperatures, earthquake catalogs, and water chemistry share the problem: the result depends on how measurement metadata and missing or censored values are handled.</p>
</div>
<aside class="notes">
<p>Two minutes, one sentence per card. Karl et al.&nbsp;(2015): over two decades the share of SST observations from drifting buoys grew, and buoys read about 0.12 °C cooler than ships in the same place; without the offset, the switch of instruments looks like a slowdown of warming after 1998, and with it the 2000–2014 trend was at least as large as the 1950–1999 trend. Hausfather et al.&nbsp;(2017, Science Advances) confirmed it with records from a single instrument type. Chan and Huybers (2021): the 1941–1945 warmth in the SST record shrinks once offsets are estimated separately for each deck and country, the same columns as on the previous slide. Woessner and Wiemer (2005): every earthquake catalog misses small events below a magnitude of completeness; slide 6 shows what that does to the b-value in the Pacific Northwest. Helsel (2006): water-quality laboratories report concentrations below the detection limit as “&lt;DL”; substituting the limit, or half of it, invents values, and survival-analysis methods use the information honestly. Rubin (1976, Biometrika) is the source of the MCAR / MAR / MNAR terms used on the gaps slide.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="tabular-data-in-the-geosciences" class="slide level2 smaller compact">
<h2>Tabular data in the geosciences</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Dataset</th>
<th>Provider</th>
<th>One data sample</th>
<th>A cleaning choice that changes results</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="gb src">🗂️ Catalog</span> <span class="gb sys solid">🪨 Solid Earth</span> earthquake catalog</td>
<td>USGS ComCat, ISC</td>
<td>one earthquake</td>
<td>magnitude cut at the completeness limit; mixed magnitude types</td>
</tr>
<tr class="even">
<td><span class="gb src">🗂️ Catalog</span> <span class="gb sys solid">🪨 Solid Earth</span> GNSS velocity table</td>
<td>NGL MIDAS</td>
<td>one station</td>
<td>reference frame; stations with short records</td>
</tr>
<tr class="odd">
<td><span class="gb src">🧪 Sample &amp; laboratory</span> <span class="gb sys solid">🪨 Solid Earth</span> whole-rock geochemistry</td>
<td>GEOROC, EarthChem</td>
<td>one rock sample</td>
<td>values below detection; iron reported as FeO, Fe2O3, or total</td>
</tr>
<tr class="even">
<td><span class="gb src">📍 In-situ sensor</span> <span class="gb sys water">💧 Land water</span> stream-gauge daily values</td>
<td>USGS NWIS</td>
<td>one day at one gauge</td>
<td>values flagged as estimated or ice-affected</td>
</tr>
<tr class="odd">
<td><span class="gb src">🧪 Sample &amp; laboratory</span> <span class="gb sys water">💧 Land water</span> water-quality analyses</td>
<td>Water Quality Portal</td>
<td>one laboratory analysis</td>
<td>concentrations reported as below the detection limit</td>
</tr>
<tr class="even">
<td><span class="gb src">📍 In-situ sensor</span> <span class="gb sys ocean">🌊 Ocean</span> ship and buoy temperatures</td>
<td>ICOADS</td>
<td>one observation</td>
<td>measurement method: bucket, engine intake, or buoy</td>
</tr>
</tbody>
</table>
<div class="takeaway">
<p>In each table, one data sample is one physical object or observation, and the columns that describe how it was measured decide how it should be cleaned.</p>
</div>
<aside class="notes">
<p>Two minutes. Ask each student which row is closest to their project data. The left column carries the source and system labels; disciplines are seismology, geodesy, geochemistry and petrology, hydrology (two rows), and oceanography and climate science. Point at the right column: none of these choices is a coding question. ComCat merges contributions from regional networks that use different magnitude scales (local, duration, moment), and its completeness changes with station density. MIDAS reports the same station velocity in a global frame and in plate-fixed frames (session 1, P395). GEOROC and EarthChem compile analyses from many laboratories, which report iron differently and flag detection limits differently; oxides that sum to 100 wt% also build negative correlations into the table (Chayes, 1960, JGR, the closure problem). NWIS daily values carry qualification codes such as “e” for estimated and “Ice” for ice-affected. The Water Quality Portal reports nondetects with a detection-condition field and a limit, not a number. ICOADS records the measurement method for each ship observation, which is what the Thompson et al.&nbsp;correction needed.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="twelve-years-of-large-earthquakes" class="slide level2">
<h2>Twelve years of large earthquakes</h2>
<div class="badge-row">
<p><span class="gb src">🗂️ Catalog &amp; compiled product</span> <span class="gb sys solid">🪨 Solid Earth</span> <span class="gb disc solid">📈 Seismology</span></p>
</div>
<img data-src="figs/2.3_pandas_rendered/global_quakes_map_slide.png" class="r-stretch">
<div class="takeaway">
<p>Deep events outline the subducting slabs. A maximum depth of 685,500 means depth is stored in meters, so the first step converts it to km.</p>
</div>
<aside class="notes">
<p>Section 2.3 compressed to one slide. The catalog is the EarthScope/IRIS event-service export kept in the UW-MLGEO dataset repository (Global_Quakes_IRIS.csv): 1,785 events of M 6 and above, 2 July 2010 to 30 June 2022, with time, latitude, longitude, depth, magnitude, and a place name. Geoscience first: shallow events outline every plate boundary; the 154 events deeper than 300 km all sit in subducting slabs (Tonga–Fiji, the Kuril–Japan–Izu–Bonin arcs, the Banda Sea, beneath South America), the Wadati–Benioff zones. The largest is the M 9.1 Tohoku-oki earthquake of 11 March 2011. Then the table: describe() reports a maximum depth of 685,500, which only makes sense in meters, hence a one-line conversion to km before anything else. The verbs to know, not the spellings: read, describe, filter, transform, group, join, map, and select by time window. Implementation names for the notebook: read_csv, describe, apply/map, groupby, agg, sort_values, plotly for the interactive map. Figure: figscripts/global_quakes_map.py fetches the catalog, PB2002 plate boundaries (Bird, 2003), and Natural Earth land at run time.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="catalog-completeness-and-the-b-value" class="slide level2">
<h2>Catalog completeness and the b-value</h2>
<div class="badge-row">
<p><span class="gb src">🗂️ Catalog &amp; compiled product</span> <span class="gb sys solid">🪨 Solid Earth</span> <span class="gb disc solid">📈 Seismology</span></p>
</div>
<img data-src="figs/2.4_dataframes_prep/pnw_catalog_completeness_slide.png" class="r-stretch">
<div class="takeaway">
<p>Keeping all 36,518 events gives b = 0.43; keeping the 16,892 events at or above M 1.0 gives b = 0.81. Hazard models use b to extrapolate from small to large earthquakes.</p>
</div>
<aside class="notes">
<p>Three minutes. Data: USGS ComCat, Washington and Oregon box (42–49.5°N, 125.5–116.5°W), M ≥ 0, 2010–2024, retrieved 2026-10-09 by figscripts/pnw_catalog_completeness.py; 99% of the events come from the Pacific Northwest Seismic Network (uw). Geoscience first: the map shows Puget Sound crustal seismicity, the Cascade volcanoes (the dense clusters at Mount St.&nbsp;Helens and Mount Hood), and scattered events in eastern Washington and Oregon. The Gutenberg–Richter law says the number of earthquakes of magnitude M or larger falls as 10^(−bM); in most tectonic regions b is close to 1. The network does not detect every small event, so below some magnitude the counts fall short of the line: that is the magnitude of completeness, Mc. Here Mc is the maximum-curvature estimate (0.8) plus 0.2, the correction Woessner and Wiemer (2005) recommend, so Mc = 1.0; 54% of the table lies below it. Fitting b with the Aki–Utsu maximum-likelihood formula on every event gives 0.43, a value that would imply far more large earthquakes per small one than the region produces; fitting above Mc gives 0.81. The map shows why a single Mc is itself a simplification: small events are detected near the dense Puget Sound and volcano-monitoring networks and missed elsewhere, so Mc varies across the region. A second cleaning issue sits in the magType column: 33,016 local magnitudes (ml) and 3,323 duration magnitudes (md) in the same table. Ask: which cleaning step would you document first?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-synthetic-rock-survey-with-known-errors" class="slide level2">
<h2>A synthetic rock survey with known errors</h2>
<div class="badge-row">
<p><span class="gb src">🧪 Sample &amp; laboratory</span> <span class="gb sys solid">🪨 Solid Earth</span> <span class="gb disc solid">⛰️ Geology &amp; geomorphology</span></p>
</div>
<div class="big-number">
<p>10,000 <span class="unit">rock samples</span></p>
</div>
<div class="big-number">
<p>5.6 : 1 <span class="unit">granites to andesites</span></p>
</div>
<p><span class="dim">Each data sample: 7 major-element oxides (wt%), bulk density, magnetic susceptibility, and a lithology label.</span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href=""></a><span class="im">import</span> mlgeo_synth</span>
<span id="cb1-2"><a href=""></a>df <span class="op">=</span> mlgeo_synth.geochem_table(n<span class="op">=</span><span class="dv">10000</span>, seed<span class="op">=</span><span class="dv">42</span>)   <span class="co"># synthetic: the true values are known</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="takeaway">
<p>Class imbalance is common in geoscience labels: a classifier that always predicts granite already scores 55%.</p>
</div>
<aside class="notes">
<p>Introduce the table: each data sample is one rock, with oxides in weight percent, bulk density, magnetic susceptibility, and a lithology label (granite, basalt, andesite) that a classifier will later predict. The badges describe what the table imitates, laboratory analyses of hand samples; the science tag says it is synthetic, and no map applies because the samples have no locations. Why synthetic: 2.4’s point is that repairs get graded. The notebook knocks out 2% of densities and 3% of susceptibilities at random and plants 15 density zeros, then checks whether cleaning recovers the truth. The imbalance seeds exercise question 3: a model that always says “granite” scores 55% accuracy (5,525 of 10,000). Physical sanity checks come first in the notebook: oxides between 0 and 100 wt%, crustal densities roughly 2.5 to 3.3 g/cm³. Read describe() against physics, always.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zeros-in-three-columns" class="slide level2">
<h2>Zeros in three columns</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Column</th>
<th>Zeros in the table</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MgO</td>
<td><strong>1,434</strong></td>
<td>real: evolved granites have fractionated their magnesium away</td>
</tr>
<tr class="even">
<td>K2O</td>
<td>824</td>
<td>real: same logic, other rock types</td>
</tr>
<tr class="odd">
<td>density</td>
<td><strong>15</strong></td>
<td>impossible: no rock has zero density, so this is an instrument’s failure code</td>
</tr>
</tbody>
</table>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href=""></a>numeric_cols <span class="op">=</span> df.select_dtypes(include<span class="op">=</span><span class="st">"number"</span>).columns</span>
<span id="cb2-2"><a href=""></a>(df[numeric_cols] <span class="op">==</span> <span class="dv">0</span>).<span class="bu">sum</span>()                       <span class="co"># zeros per column</span></span>
<span id="cb2-3"><a href=""></a>df.loc[df[<span class="st">"MGO"</span>] <span class="op">==</span> <span class="dv">0</span>, <span class="st">"label"</span>].value_counts()       <span class="co"># which rocks have MgO = 0?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="takeaway">
<p>Replacing every zero with a missing value, then dropping incomplete samples, would remove 1,432 silica-rich granites from the table.</p>
</div>
<aside class="notes">
<p>The tempting shortcut is a global zeros-to-missing sweep; walk through why it fails, column by column. The MgO zeros sit almost entirely in granites (1,432 of 1,434), and those granites are silica-rich: median SiO2 of 74.2 wt% against 69.2 for the full table. That is textbook petrology: evolved melts run out of Mg, so these zeros are measurements. The 15 density zeros are the opposite. They are physically impossible, so they are sentinel codes, a database’s way of writing “no measurement” inside the data values. Real archives use 0, −999, −9999; the fingerprint is a heap at an impossible or suspiciously round value. Fix: replace only the impossible ones with an explicit missing marker. Numbers rerun on Oct 7 from mlgeo_synth.geochem_table(n=10000, seed=42) and the notebook’s planting step.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="values-censored-at-a-reporting-floor" class="slide level2">
<h2>Values censored at a reporting floor</h2>
<img data-src="figs/2.4_dataframes_prep/censored_series_slide.png" class="r-stretch">
<div class="dim">
<p>Synthetic (mlgeo_synth): a displacement series moving at 12 mm/yr, reported through a 5 mm floor.</p>
</div>
<div class="takeaway">
<p>12% of samples sit exactly at the 5 mm floor, and a missing-value check finds none: censored values are numbers, so missingness tests cannot detect them.</p>
</div>
<aside class="notes">
<p>Define censoring aloud: the instrument reports a number, but the number is the reporting floor, not the measurement. Geochemical analyses write “&lt;0.01” as 0.01; stream gauges floor out at low flow. Be straight about the example: a GNSS position has no such floor, so this is a GNSS-shaped series with a floor imposed to make the bias measurable; the real cases are laboratory detection limits (trace elements, nutrients, contaminants) and gauges at low flow. Left panel: the reported series (red) rides the dashed floor whenever the true series (gray) dips below it. Right panel: the fingerprint, a heap of identical values exactly at the limit, the same signature as the sentinel zeros one slide ago, but at a value that is plausible instead of impossible. Because the value is plausible, nothing in a summary table flags it. The generator returns the uncensored truth, so the next slide can measure the damage exactly.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="effect-of-the-floor-on-the-fitted-trend" class="slide level2">
<h2>Effect of the floor on the fitted trend</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Series used for the fit</th>
<th style="text-align: right;">Trend (mm/yr)</th>
<th style="text-align: right;">Year-1 mean (mm)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>True, uncensored</td>
<td style="text-align: right;"><strong>12.44</strong></td>
<td style="text-align: right;"><strong>4.80</strong></td>
</tr>
<tr class="even">
<td>Reported, floor values kept</td>
<td style="text-align: right;">11.59</td>
<td style="text-align: right;">7.24</td>
</tr>
<tr class="odd">
<td>Reported, floor values dropped</td>
<td style="text-align: right;">11.82</td>
<td style="text-align: right;">9.29</td>
</tr>
</tbody>
</table>
<div class="dim">
<p>Both shortcuts raise the early values and lower the trend. Dropping the floor values worsens the year-1 mean and slightly improves the trend; neither recovers the true values.</p>
</div>
<div class="takeaway">
<p>Use a method that treats “below 5 mm” as information, or report the limit in the data card so later users can.</p>
</div>
<aside class="notes">
<p>The bias has a sign you can work out in advance. Censoring only ever pulls low values up, so first-year statistics inflate and the trend deflates. Ask the room to predict the third row before revealing it. Dropping removes the low tail entirely, so the year-1 mean rises further (9.29 against 7.24, truth 4.80); the trend improves a little (11.82 against 11.59) because the dropped samples were the ones dragging the early fit up, but it is still 0.6 mm/yr low, and which statistic suffers depends on what you compute. Neither shortcut is safe in general. Honest options: survival or tobit-type methods that treat “below L” as the datum it is, or at minimum reporting the limit alongside the data so downstream users can. Related trap: a mid-record instrument swap changes the floor mid-series, so a step in a record’s variance is a metadata question before it is a discovery. All six numbers rerun on Oct 7: mlgeo_synth.gnss_series(n_years=4, velocity_mm_yr=12.0, seed=7) through degrade_series(detection_limit_mm=5.0, seed=7), least-squares line on 1,461 daily samples (1,286 after dropping).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="gaps-caused-by-the-measured-quantity" class="slide level2">
<h2>Gaps caused by the measured quantity</h2>
<ul>
<li>A stream gauge fails during the flood it was installed to measure</li>
<li>A GNSS antenna stops recording under a storm’s snow load</li>
<li>A field crew skips a location when the road washes out</li>
</ul>
<div class="dim">
<p>Missing completely at random (MCAR): safe to drop. Missing <em>because of</em> the value (MNAR): dropping deletes your extremes.</p>
</div>
<div class="takeaway">
<p>For each gap pattern, state what caused it. If the cause depends on the measured quantity, dropping those samples removes the extremes, and the data card should say so.</p>
</div>
<aside class="notes">
<p>Rubin’s vocabulary, on geoscience instruments. The planted gaps in 2.4 are MCAR by construction; that is what licenses dropna in the notebook, and the text says so. Real instruments rarely oblige: each bullet is a case where the gap is caused by the value that would have been measured, so dropping rows systematically deletes floods, storms, and washouts, the events the analysis probably exists to study. Connect backward: the MgO zeros were the same idea inverted, “suspicious” values concentrated in one geology, so removing them rewrites the field. The operational habit: for every gap pattern, write one sentence on its mechanism; if the sentence mentions the measured quantity, the missingness policy is a scientific decision to defend, not a default.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="cleaning-can-change-a-columns-type" class="slide level2">
<h2>Cleaning can change a column’s type</h2>
<ul>
<li>Replacing the impossible density zeros with a missing marker is the right fix</li>
<li>pandas then changes the column’s storage type from <strong>float64 to object</strong> (numbers stored as generic objects), without a message</li>
<li>Later steps that use only numeric columns, such as correlations and summaries, <em>drop density without a warning</em></li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href=""></a>df <span class="op">=</span> df.replace({<span class="st">"density_g_cm3"</span>: {<span class="fl">0.0</span>: pd.NA}})</span>
<span id="cb3-2"><a href=""></a>df[<span class="st">"density_g_cm3"</span>].dtype                            <span class="co"># object, no longer float64</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="takeaway">
<p>Check column types after each cleaning step: a column of numbers can be stored as a non-numeric type.</p>
</div>
<aside class="notes">
<p>The notebook plants this bug on purpose. The cleaning that protected density (zeros to missing) changed its storage type; from then on, any select-numeric-columns operation, the correlation matrices and describe(), excludes the column the cleaning was meant to protect, with no error or warning, so the analysis loses a variable. The fix is one cast back to numeric, and the habit to teach is checking dtypes after every step. This is also the modern-pandas moment: assign results (df = df.replace(…)) rather than mutating in place, because chained in-place edits on slices raise errors in pandas 3. Downstream payoff of a clean table: the correlation matrices show the planted geochemistry (SiO2 anticorrelates with FeO, MgO, CaO), plus the closure effect: oxides sum to about 100 wt%, which builds anticorrelation into the table regardless of petrology. That subtlety is exercise question 1.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="four-kinds-of-bad-values-and-how-to-detect-them" class="slide level2 smaller">
<h2>Four kinds of bad values and how to detect them</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Pathology</th>
<th>Fingerprint</th>
<th>Geoscience example</th>
<th>Response</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Sentinel value</strong></td>
<td>heap at an impossible value</td>
<td>density = 0 g/cm³</td>
<td>replace only the impossible ones</td>
</tr>
<tr class="even">
<td><strong>Censored value</strong></td>
<td>heap at a plausible round value</td>
<td>laboratory detection limit</td>
<td>model it, or report the limit</td>
</tr>
<tr class="odd">
<td><strong>Informative gap</strong></td>
<td>gaps track events</td>
<td>gauge drowned in the flood</td>
<td>treat the gap as data</td>
</tr>
<tr class="even">
<td><strong>Dtype drift</strong></td>
<td>numeric content, non-numeric dtype</td>
<td>density after cleaning</td>
<td>check dtypes every step</td>
</tr>
</tbody>
</table>
<div class="takeaway">
<p>In each case, find out what produced the values before changing them, and record the change.</p>
</div>
<aside class="notes">
<p>The lecture in one screen; leave it up for questions. Each row was a slide. The connecting idea is that every pathology has a mechanism (a failing instrument, a reporting floor, a physical cause, a library behavior) and a fingerprint you can test for, and that the response is a documented decision, not a reflex. This table becomes part of the 2.13 data-card checklist and is applied to each team’s own project data at check-in 1. The censoring and gap rows return Monday on time series, where the same mistakes cost an error we can measure.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-each-cleaning-choice-changed" class="slide level2 smaller compact">
<h2>What each cleaning choice changed</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Choice</th>
<th>Data</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>keep events below the completeness limit</td>
<td>Pacific Northwest earthquakes, ComCat</td>
<td>b-value 0.43 instead of 0.81</td>
</tr>
<tr class="even">
<td>combine ship measurement methods without correction</td>
<td>sea surface temperature, ICOADS</td>
<td>drop of about 0.3 °C in late 1945 (Thompson et al., 2008)</td>
</tr>
<tr class="odd">
<td>ignore the ship–buoy offset</td>
<td>sea surface temperature, ERSST</td>
<td>apparent slowdown of warming after 1998</td>
</tr>
<tr class="even">
<td>replace all zeros, then drop incomplete samples</td>
<td>rock survey (synthetic)</td>
<td>1,432 granites removed</td>
</tr>
<tr class="odd">
<td>keep values at the reporting floor</td>
<td>GNSS-shaped series (synthetic)</td>
<td>trend 11.59 instead of 12.44 mm/yr</td>
</tr>
<tr class="even">
<td>substitute the detection limit for nondetects</td>
<td>water-quality analyses</td>
<td>biased means and trends</td>
</tr>
</tbody>
</table>
<div class="takeaway">
<p>Each choice changed a number that a scientific conclusion depends on. Record the rule, how many values it changed, and why, so that another analyst can repeat the analysis with a different choice.</p>
</div>
<aside class="notes">
<p>Two minutes; leave it up while moving to the notebook. The first three rows are real geoscience data and published or reproducible results (this lecture’s figure; Thompson et al., 2008; Karl et al., 2015); the next two are the synthetic examples, where the true values are known; the last is Helsel (2006). The point for projects: a cleaning step is part of the method, and its effect can be measured by running the analysis both ways, as the b-value slide did. That record belongs in the data card (2.13) and in the cleaning log named on the next slide.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="cleaning-rules-your-agent-must-follow" class="slide level2">
<h2>Cleaning rules your agent must follow</h2>
<p>Ask an assistant to “clean this table” and the likely result is the global sweep: zeros to missing, then drop incomplete samples.</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>A rule that cannot be checked</th>
<th>A rule that can</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Clean the data carefully</td>
<td>Replace a value only if it lies outside the physical range stated in <code>data/README.md</code></td>
</tr>
<tr class="even">
<td>Handle missing values</td>
<td>Log every replacement or drop (column, rule, count) to <code>cleaning_log.csv</code></td>
</tr>
<tr class="odd">
<td>Fix the types</td>
<td>Report <code>df.dtypes</code> before and after each cleaning step</td>
</tr>
</tbody>
</table>
<div class="takeaway">
<p>If AGENTS.md states no cleaning rule, an assistant applies its default: the global sweep from the zeros slide.</p>
</div>
<aside class="notes">
<p>Three minutes, 🤝 assistant allowed. This links today to Monday’s AGENTS.md (HW1 Step 7, due Monday Oct 12). The left column is what most people would type; none of it can be settled by reading the agent’s output, so it does not count toward the five rules. The right column can be checked against the commits and the log. Ask each student to write one data-cleaning rule for their own project data and add it to their AGENTS.md before Monday; the peer who reran their repository on Wednesday is the right person to check it. Return to the opening question: the rules people described for deleting rows are exactly what belongs here.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="run-notebook-2.4" class="slide level2">
<h2>Run notebook 2.4</h2>
<ol type="1">
<li><code>pixi run jupyter lab</code> → <code>2.4_dataframes_prep.ipynb</code></li>
<li>Run the cleaning: count the zeros, replace only the impossible ones, catch the dtype change and fix it</li>
<li>Reproduce the censoring bias (11.59 vs 12.44 mm/yr), then drop the floor values: predict first which statistic gets worse, the trend or the year-1 mean</li>
<li>Exercise Q3: what accuracy does “always predict granite” achieve, and what does that imply for evaluating any classifier on this table?</li>
<li>Write one checkable cleaning rule into your AGENTS.md</li>
</ol>
<div class="dim">
<p>Monday: sampling, resampling, and irregular data (2.5–2.6) · HW1 due Mon Oct 12</p>
</div>
<aside class="notes">
<p>Timing for the 80-minute block (10:00–11:20): pulse-talk sign-ups are open, no talks yet. Admin about 7 minutes, deck about 20, guided notebook about 40 (task 3 is where the learning is: circulate and ask students to commit to a prediction before running), synthesis about 13 on tasks 4 and 5. Task 4’s answer (55%) seeds the class-imbalance thread that runs to Chapter 3; collect two or three AGENTS.md rules from task 5 and test them against the left/right columns of the previous slide. Implementation names live here: isna/dropna, replace with pd.NA, pd.to_numeric, select_dtypes, corr(method=‘spearman’), value_counts. 2.3’s remaining levels (plotly maps, station-metadata parsing) are self-guided. Remind: HW1 due Monday, including the AGENTS.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>ESS 469/569 · Machine Learning in the Geosciences · Autumn 2026</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="lec05_tables_that_tell_the_truth_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="lec05_tables_that_tell_the_truth_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="lec05_tables_that_tell_the_truth_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="lec05_tables_that_tell_the_truth_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="lec05_tables_that_tell_the_truth_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="lec05_tables_that_tell_the_truth_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="lec05_tables_that_tell_the_truth_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="lec05_tables_that_tell_the_truth_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="lec05_tables_that_tell_the_truth_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="lec05_tables_that_tell_the_truth_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 4.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>