name: curriculum_book
channels:
  - conda-forge
dependencies:
  - python=3.10
  - sphinxcontrib-bibtex
  - jupyter-book=0.13
  - jupytext
  # https://github.com/executablebooks/jupyter-book/issues/1907
  - jupyter_server<2
  - scikit-learn
  - plotly=5.10.0
  - pandas
  - pycaret # for chapter 3.8
  - scikit-learn
platforms:
  - linux-64
  - osx-64
