"""Generate the book's Lectures chapter from the slide decks.

One page per deck in book/slides/2026/lec*.qmd, in session order, plus an
overview table. Everything comes from each deck's front matter:
  title:    "Meet the data:<br>streams, formats, and a first real dataset"
  subtitle: "Session 4 · Wed Oct 7 · Book sections 2.1–2.2 & 1.6–1.7"
Book section numbers are resolved to the book pages that carry them, so the
links follow the sessions' order rather than the chapters'.

Run after adding or retitling a deck, then commit the output:
    pixi run python tools/gen_lecture_pages.py
"""
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
BOOK = ROOT / "book"
DECKS = BOOK / "slides" / "2026"
OUT = BOOK / "Lectures"
SITE = "https://geo-smart.github.io/mlgeo-book/slides/2026"
YEAR = 2026
HEADER = "<!-- Generated by tools/gen_lecture_pages.py from the deck front matter. Do not edit by hand. -->\n\n"


def front_matter(path):
    text = path.read_text()
    return yaml.safe_load(text.split("---", 2)[1])


def section_files():
    """Map '2.6' -> path relative to book/, from file names like 2.6_x or mlgeo_4.3_x."""
    out = {}
    for f in sorted(BOOK.glob("Chapter*/*")) + sorted(BOOK.glob("about_this_book/*")):
        m = re.match(r"(?:mlgeo_)?(\d+\.\d+)_", f.name)
        if m and f.suffix in (".md", ".ipynb"):
            out.setdefault(m.group(1), f.relative_to(BOOK).as_posix())
    return out


def expand(spec):
    """'2.1–2.2 & 1.6–1.7' -> ['2.1', '2.2', '1.6', '1.7']; '3.7 + 3.9 (3.10 flipped)' keeps 3.10."""
    nums = []
    for a, b in re.findall(r"(\d+\.\d+)(?:\s*[–-]\s*(\d+\.\d+))?", spec):
        if b and a.split(".")[0] == b.split(".")[0]:
            ch, lo, hi = a.split(".")[0], int(a.split(".")[1]), int(b.split(".")[1])
            nums += [f"{ch}.{i}" for i in range(lo, hi + 1)]
        else:
            nums += [a] + ([b] if b else [])
    return list(dict.fromkeys(nums))


def main():
    files = section_files()
    decks = []
    for q in sorted(DECKS.glob("lec*.qmd")):
        fm = front_matter(q)
        title = re.sub(r"\s+", " ", fm["title"].replace("<br>", " ")).strip()
        session, date, sections = [p.strip() for p in fm["subtitle"].split("·")]
        nums = expand(sections)
        links = [f"[{n}](../{files[n]})" for n in nums if n in files]
        missing = [n for n in nums if n not in files]
        decks.append(dict(stem=q.stem, n=int(session.split()[1]), title=title, date=date,
                          sections=sections, links=links, missing=missing))
    decks.sort(key=lambda d: d["n"])

    OUT.mkdir(exist_ok=True)
    for d in decks:
        url = f"{SITE}/{d['stem']}.html"
        note = f" (sections {', '.join(d['missing'])} have no book page yet)" if d["missing"] else ""
        page = (f"---\ntitle: \"Session {d['n']} · {d['title']}\"\n---\n\n" + HEADER +
                f"**{d['date']}, {YEAR}** · Book sections: {' · '.join(d['links']) or d['sections']}{note}\n\n"
                f"🖥️ [Open the slides in a new tab]({url}) · press `S` for speaker notes, `Esc` for the slide overview\n\n"
                f":::{{iframe}} {url}\n:width: 100%\n:::\n")
        (OUT / f"{d['stem']}.md").write_text(page)

    rows = "\n".join(f"| {d['n']} | {d['date']} | [{d['title']}]({d['stem']}.md) | {' · '.join(d['links'])} |"
                     for d in decks)
    (OUT / "readme.md").write_text(
        f"---\ntitle: Lectures (Autumn {YEAR})\n---\n\n" + HEADER +
        "The course meets three times a week, and the sessions draw on the book out of chapter order: "
        "session 3, for example, combines 1.8 with 6.1, and session 11 brings 6.2 into the middle of the data chapter. "
        "This chapter lists the slide decks in the order they are taught, each with the book sections it uses. "
        "Sessions without slides (project check-ins, presentations) and all graded deadlines are on the "
        "[course schedule](../about_this_book/schedule_fall2026.md).\n\n"
        "| Session | Date | Slides | Book sections |\n|---|---|---|---|\n" + rows + "\n")
    print(f"wrote {len(decks)} lecture pages to {OUT.relative_to(ROOT)}")
    for d in decks:
        if d["missing"]:
            print(f"  session {d['n']}: no book page for {d['missing']}")


if __name__ == "__main__":
    main()
