name: Clean

on:
  push:
    paths:
      - 'book/**'
      - '.github/workflows/clean.yaml'
      - '.github/actions/**'

    branches:
      - main

jobs:
  push-to-student-repo:
    if: github.repository == 'geo-smart/curriculum-book'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Move files to be pushed to /output directory
      shell: bash
      run: |
        rsync -arv --exclude=".git" . output/

    - name: Push to student repo
      uses:  StefanTodoran/github-action-force-push-to-other-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.STUDENT_BOOK_KEY }}
      with:
        source-directory: output/
        destination-github-username: 'geo-smart'
        destination-repository-name: 'curriculum-book-student'
        user-email: action@github.com
        commit-message: update student version with curriculum book changes
        target-branch: main

  clean-and-deploy:
    if: github.repository == 'geo-smart/curriculum-book-student'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: ./.github/actions/studentversion
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: ./.github/actions/buildresources
      with:
        jb-cache: false
        publish-to-gh: true
        jb-save: true
        token: ${{ secrets.GITHUB_TOKEN }}
